# Generated by Django 5.2.5 on 2025-09-03 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('networking', 'Networking'), ('round_table', 'Round Table'), ('startup_discussion', 'Startup Discussion'), ('campus_tour', 'Campus Tour / Meetup'), ('social', 'Social'), ('family_friends', 'Family / Friends Event')], max_length=50)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('event_end_date', models.DateTimeField(blank=True, null=True)),
                ('location_type', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], max_length=10)),
                ('physical_address', models.CharField(blank=True, max_length=200, null=True)),
                ('online_link', models.URLField(blank=True, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_register_number', models.CharField(default='UNKNOWN', max_length=50)),
                ('roll_no', models.CharField(default='UNKNOWN', max_length=50)),
                ('f_name', models.CharField(default='N/A', max_length=100)),
                ('lname', models.CharField(default='N/A', max_length=100)),
                ('student_name', models.CharField(default='N/A', max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10)),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('mobile_number', models.CharField(default='0000000000', max_length=15)),
                ('state', models.CharField(default='N/A', max_length=50)),
                ('email_id', models.EmailField(default='example@example.com', max_length=254)),
                ('father_name', models.CharField(default='N/A', max_length=200)),
                ('father_mobile_number', models.CharField(default='0000000000', max_length=15)),
                ('father_occupation', models.CharField(default='N/A', max_length=100)),
                ('father_organization', models.CharField(default='N/A', max_length=200)),
                ('mother_name', models.CharField(default='N/A', max_length=200)),
                ('mother_mobile_number', models.CharField(default='0000000000', max_length=15)),
                ('mother_occupation', models.CharField(default='N/A', max_length=100)),
                ('mother_organization', models.CharField(default='N/A', max_length=200)),
                ('batch', models.CharField(default='N/A', max_length=20)),
                ('department', models.CharField(default='N/A', max_length=100)),
                ('current_location', models.CharField(default='N/A', max_length=200)),
                ('current_company', models.CharField(default='N/A', max_length=200)),
                ('designation', models.CharField(default='N/A', max_length=100)),
                ('position', models.CharField(default='N/A', max_length=100)),
                ('job_domain', models.CharField(default='N/A', max_length=100)),
                ('phone_number', models.CharField(default='0000000000', max_length=15)),
                ('phone_number2', models.CharField(default='1000000000', max_length=15)),
                ('personal_email_id', models.EmailField(default='example@example.com', max_length=254)),
                ('official_email_id', models.EmailField(default='example@example.com', max_length=254)),
                ('linkedin_link', models.URLField(default='http://example.com')),
            ],
        ),
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beverages', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('speaker', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='events.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('requires_payment', models.BooleanField(default=False)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('event_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_definitions', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('textarea', 'Textarea'), ('date', 'Date'), ('file', 'File'), ('dropdown', 'Dropdown')], max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('choices', models.TextField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='events.formdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='events.formdefinition')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('status', models.CharField(default='pending', max_length=254, verbose_name='Payment Status')),
                ('provider_order_id', models.CharField(max_length=40, verbose_name='Order ID')),
                ('payment_id', models.CharField(max_length=36, verbose_name='Payment ID')),
                ('signature_id', models.CharField(max_length=128, verbose_name='Signature ID')),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('intiated', 'Intiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_registered_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.formsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.dynamicfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='events.formsubmission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
