# Generated by Django 5.2.5 on 2025-09-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='max_submissions_per_user',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
