# Generated by Django 5.2.5 on 2025-09-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_student_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_status',
            field=models.CharField(choices=[('private', 'Working in private organization'), ('business', 'Business/Entrepreneur'), ('education', 'Pursuing Higher Education'), ('others', 'Others')], default='other', max_length=20),
        ),
    ]
