# Generated by Django 5.2.5 on 2025-09-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_about_alter_agendaitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='designation',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_status_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
