# Generated by Django 5.2.5 on 2025-09-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_student_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_location',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='designation',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
